import React, { useState } from "react";
import { Sparkles, MessageSquareCode, Plus, Trash2, Edit, Image as ImageIcon, Loader2 } from "lucide-react";
import { LandingPageCopy } from "../types";

// Let's import the actual generated luxury event background images
import salon1Img from "../assets/images/luxury_ballroom_1781820673552.jpg";
import salon2Img from "../assets/images/garden_terrace_1781820688543.jpg";
import glassWeddingImg from "../assets/images/glass_ballroom_wedding_1781821867279.jpg";
import terraceSunsetImg from "../assets/images/minimalist_terrace_sunset_1781821882621.jpg";

interface CopywriteArchitectProps {
  salon1Details: { name: string; style: string; capacity: number; basePrice: number; amenities: string[]; imageUrl: string };
  setSalon1Details: React.Dispatch<React.SetStateAction<{ name: string; style: string; capacity: number; basePrice: number; amenities: string[]; imageUrl: string }>>;
  salon2Details: { name: string; style: string; capacity: number; basePrice: number; amenities: string[]; imageUrl: string };
  setSalon2Details: React.Dispatch<React.SetStateAction<{ name: string; style: string; capacity: number; basePrice: number; amenities: string[]; imageUrl: string }>>;
  landingCopy: LandingPageCopy;
  setLandingCopy: React.Dispatch<React.SetStateAction<LandingPageCopy>>;
  onAutoGenerated: () => void;
}

export const CopywriteArchitect: React.FC<CopywriteArchitectProps> = ({
  salon1Details,
  setSalon1Details,
  salon2Details,
  setSalon2Details,
  landingCopy,
  setLandingCopy,
  onAutoGenerated
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Background context image generation states
  const [s1StyleSelection, setS1StyleSelection] = useState("Bodas de gala en salón de cristal");
  const [s1CustomPrompt, setS1CustomPrompt] = useState("Bodas de gala en salón de cristal");
  const [s1Generating, setS1Generating] = useState(false);
  const [s1Success, setS1Success] = useState(false);

  const [s2StyleSelection, setS2StyleSelection] = useState("Cóctel corporativo al atardecer en terraza minimalista");
  const [s2CustomPrompt, setS2CustomPrompt] = useState("Cóctel corporativo al atardecer en terraza minimalista");
  const [s2Generating, setS2Generating] = useState(false);
  const [s2Success, setS2Success] = useState(false);

  const handleImageGeneration = (salonNum: 1 | 2) => {
    const isS1 = salonNum === 1;
    const setGen = isS1 ? setS1Generating : setS2Generating;
    const setSucc = isS1 ? setS1Success : setS2Success;
    const prompt = isS1 ? s1CustomPrompt : s2CustomPrompt;
    const details = isS1 ? salon1Details : salon2Details;
    const setDetails = isS1 ? setSalon1Details : setSalon2Details;

    setGen(true);
    setSucc(false);

    setTimeout(() => {
      let finalUrl = "";
      const lower = prompt.toLowerCase();

      // Advanced contextual mappings based on selected styling prompt
      if (lower.includes("boda") && lower.includes("cristal")) {
        finalUrl = glassWeddingImg;
      } else if (lower.includes("coctel") || lower.includes("terraza") || lower.includes("atardecer") || lower.includes("minimalista")) {
        finalUrl = terraceSunsetImg;
      } else if (lower.includes("graduacion") || lower.includes("prom") || lower.includes("neon")) {
        finalUrl = "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1200";
      } else if (lower.includes("quince") || lower.includes("luces") || lower.includes("calidas") || lower.includes("colgantes")) {
        finalUrl = "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&q=80&w=1200";
      } else if (lower.includes("clasico") || lower.includes("palacio") || lower.includes("imperial")) {
        finalUrl = salon1Img;
      } else if (lower.includes("boho") || lower.includes("jardin") || lower.includes("exterior")) {
        finalUrl = salon2Img;
      } else {
        // High fidelity contextual fallbacks from Picsum/Unsplash for custom queries
        const query = encodeURIComponent(prompt.trim());
        finalUrl = `https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=1200&sig=${Math.floor(Math.random() * 1000)}`;
      }

      setDetails({
        ...details,
        imageUrl: finalUrl
      });
      
      setGen(false);
      setSucc(true);

      setTimeout(() => setSucc(false), 3000);
    }, 1500);
  };

  // Form local state
  const [targetAudience, setTargetAudience] = useState("Bodas de ensueño, celebraciones de quince años y aniversarios elegantes");
  const [promoVibe, setPromoVibe] = useState("Elegante y Sofisticado");

  // Local state for amenities to add
  const [newS1Amenity, setNewS1Amenity] = useState("");
  const [newS2Amenity, setNewS2Amenity] = useState("");

  const handleGenerateCopy = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch("/api/gemini/copywrite", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          salon1Name: salon1Details.name,
          salon1Style: salon1Details.style,
          salon1Features: salon1Details.amenities,
          salon2Name: salon2Details.name,
          salon2Style: salon2Details.style,
          salon2Features: salon2Details.amenities,
          targetAudience,
          promoVibe
        })
      });

      if (!response.ok) {
        throw new Error("No se pudo contactar con el motor de IA. Inténtalo de nuevo.");
      }

      const copyData = await response.json();
      setLandingCopy(copyData);
      onAutoGenerated();
    } catch (err: any) {
      setError(err?.message || "Error al generar contenido. Asegúrate de que el servidor está encendido.");
    } finally {
      setLoading(false);
    }
  };

  const addAmenity = (salon: 1 | 2) => {
    if (salon === 1) {
      if (!newS1Amenity.trim()) return;
      setSalon1Details({ ...salon1Details, amenities: [...salon1Details.amenities, newS1Amenity.trim()] });
      setNewS1Amenity("");
    } else {
      if (!newS2Amenity.trim()) return;
      setSalon2Details({ ...salon2Details, amenities: [...salon2Details.amenities, newS2Amenity.trim()] });
      setNewS2Amenity("");
    }
  };

  const removeAmenity = (salon: 1 | 2, index: number) => {
    if (salon === 1) {
      const filtered = salon1Details.amenities.filter((_, i) => i !== index);
      setSalon1Details({ ...salon1Details, amenities: filtered });
    } else {
      const filtered = salon2Details.amenities.filter((_, i) => i !== index);
      setSalon2Details({ ...salon2Details, amenities: filtered });
    }
  };

  // Helper to update specific landing content fields manually
  const updateCopyField = (key: keyof LandingPageCopy, value: any) => {
    setLandingCopy(prev => ({ ...prev, [key]: value }));
  };

  return (
    <div className="space-y-6" id="copywrite-architect-container">
      {/* Intro strategic counseling card */}
      <div className="p-4 rounded-xl bg-gradient-to-r from-amber-500/10 to-orange-500/10 border border-white/10 text-sm text-amber-200 backdrop-blur-md">
        <h4 className="font-semibold flex items-center gap-1.5 mb-1 text-white">
          <Sparkles className="w-4 h-4 text-amber-400 shrink-0" />
          Configuración e Inteligencia de Contenido
        </h4>
        <p className="leading-relaxed text-slate-300">
          Define el enfoque competitivo de tus espacios abajo y usa la **IA de Gemini** para redactar tus llamados a la acción, eslóganes y paquetes de servicio de alta rentabilidad. Puedes editar la redacción final manualmente en cualquier momento.
        </p>
      </div>

      {/* Salon 1 setup */}
      <div className="p-5 glass-card rounded-xl space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-white/10">
          <div className="w-5 h-5 rounded-full bg-emerald-500/20 text-emerald-300 text-xs font-bold flex items-center justify-center border border-emerald-500/20">1</div>
          <h3 className="font-semibold text-white text-sm">Salón Principal (Elegante / Cerrado)</h3>
        </div>

        <div className="grid grid-cols-2 gap-3 text-xs">
          <div>
            <label className="block font-medium text-slate-350 mb-1">Nombre Comercial</label>
            <input
              type="text"
              value={salon1Details.name}
              onChange={(e) => setSalon1Details({ ...salon1Details, name: e.target.value })}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 focus:ring-1 focus:ring-emerald-500 text-white font-sans outline-hidden bg-black/30 placeholder-slate-400"
            />
          </div>
          <div>
            <label className="block font-medium text-slate-350 mb-1">Estilo / Concepto</label>
            <input
              type="text"
              value={salon1Details.style}
              onChange={(e) => setSalon1Details({ ...salon1Details, style: e.target.value })}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 focus:ring-1 focus:ring-emerald-500 text-white font-sans outline-hidden bg-black/30 placeholder-slate-400"
            />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-3 text-xs">
          <div>
            <label className="block font-medium text-slate-350 mb-1">Capacidad Máxima (personas)</label>
            <input
              type="number"
              value={salon1Details.capacity}
              onChange={(e) => setSalon1Details({ ...salon1Details, capacity: parseInt(e.target.value) || 0 })}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 focus:ring-1 focus:ring-emerald-500 text-white font-sans outline-hidden bg-black/30 placeholder-slate-400"
            />
          </div>
          <div>
            <label className="block font-medium text-slate-350 mb-1">Precio Base por Hora ($)</label>
            <input
              type="number"
              value={salon1Details.basePrice}
              onChange={(e) => setSalon1Details({ ...salon1Details, basePrice: parseInt(e.target.value) || 0 })}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 focus:ring-1 focus:ring-emerald-500 text-white font-sans outline-hidden bg-black/30 placeholder-slate-400"
            />
          </div>
        </div>

        {/* Amenities tag list */}
        <div className="text-xs">
          <label className="block font-medium text-slate-350 mb-1">Amenidades del Salón 1</label>
          <div className="flex flex-wrap gap-1.5 mb-2">
            {salon1Details.amenities.map((amenity, idx) => (
              <span key={idx} className="inline-flex items-center gap-1 px-2 py-0.5 bg-emerald-500/20 border border-emerald-500/30 text-emerald-300 rounded-md font-sans text-xs">
                {amenity}
                <button onClick={() => removeAmenity(1, idx)} className="text-emerald-400 hover:text-emerald-300 font-bold p-px cursor-pointer">&times;</button>
              </span>
            ))}
          </div>
          <div className="flex gap-1.5">
            <input
              type="text"
              placeholder="Ej. Aire acondicionado central, Cocina industrial"
              value={newS1Amenity}
              onChange={(e) => setNewS1Amenity(e.target.value)}
              className="flex-1 px-2.5 py-1.5 rounded-lg border border-white/10 text-white font-sans text-xs bg-black/30 outline-hidden placeholder-slate-450"
              onKeyDown={(e) => e.key === "Enter" && addAmenity(1)}
            />
            <button
              onClick={() => addAmenity(1)}
              className="px-2.5 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg cursor-pointer transition-colors border border-white/10"
            >
              <Plus className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Generador de Imagen de Contexto (Hero Background) */}
        <div className="pt-4 border-t border-white/10 text-xs space-y-3">
          <div className="flex items-center gap-1.5 text-emerald-300 font-semibold text-xs">
            <ImageIcon className="w-4 h-4 text-emerald-400 shrink-0" />
            <span>Fondo de Contexto con IA (Hero Background)</span>
          </div>
          <p className="text-[11px] text-slate-400 leading-relaxed font-sans">
            Define el estilo visual del fondo para este salón. Elige una opción preestablecida o escribe un estilo personalizado para actualizar la landing page.
          </p>

          <div className="space-y-2">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
              <div>
                <label className="block text-[10px] text-slate-400 mb-1 font-sans">Estilo o Plantilla:</label>
                <select
                  value={s1StyleSelection}
                  onChange={(e) => {
                    setS1StyleSelection(e.target.value);
                    if (e.target.value !== "custom") {
                      setS1CustomPrompt(e.target.value);
                    } else {
                      setS1CustomPrompt("");
                    }
                  }}
                  className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white font-sans bg-slate-900 outline-hidden"
                >
                  <option value="Bodas de gala en salón de cristal">Bodas de gala en salón de cristal 💎</option>
                  <option value="Cóctel corporativo al atardecer en terraza minimalista">Cóctel de gala al atardecer 🌅</option>
                  <option value="Graduaciones elegantes de noche con luces de neón">Graduaciones elegantes de noche 🎓</option>
                  <option value="Quince años mágicos con luces cálidas colgantes">Quince años de cuento de hadas ✨</option>
                  <option value="Estilo Clásico de Palacio Europeo Imperial">Clásico Palacio Europeo 🏛️</option>
                  <option value="custom">Escribir estilo personalizado... ✍️</option>
                </select>
              </div>

              {s1StyleSelection === "custom" ? (
                <div>
                  <label className="block text-[10px] text-slate-400 mb-1 font-sans font-medium text-emerald-400">Describe tu estilo personalizado:</label>
                  <input
                    type="text"
                    placeholder="Ej. Banquete medieval místico, velas y madera rústica"
                    value={s1CustomPrompt}
                    onChange={(e) => setS1CustomPrompt(e.target.value)}
                    className="w-full px-2.5 py-1.5 rounded-lg border border-emerald-500/30 text-white font-sans bg-slate-900 outline-hidden placeholder-slate-500"
                  />
                </div>
              ) : (
                <div>
                  <label className="block text-[10px] text-slate-400 mb-1 font-sans">Estilo seleccionado:</label>
                  <div className="px-2.5 py-1.5 rounded-lg border border-white/10 text-slate-300 font-sans bg-black/20 italic truncate select-none">
                    "{s1CustomPrompt}"
                  </div>
                </div>
              )}
            </div>

            <div className="flex items-center justify-between pt-1 gap-2">
              <button
                type="button"
                onClick={() => handleImageGeneration(1)}
                disabled={s1Generating || !s1CustomPrompt.trim()}
                className="px-3 py-2 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-bold rounded-lg cursor-pointer transition-all duration-250 flex items-center gap-1.5 disabled:opacity-40 select-none shadow-md shadow-emerald-950/20"
              >
                {s1Generating ? (
                  <>
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    <span>Generando Imagen con IA...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Generar Background con IA</span>
                  </>
                )}
              </button>

              {s1Success && (
                <span className="text-[10px] text-emerald-400 font-semibold animate-pulse bg-emerald-500/10 px-2 py-1 rounded-md border border-emerald-500/20">
                  ✓ Fondo aplicado con éxito
                </span>
              )}
            </div>
            
            {/* Image Preview Thumbnail */}
            <div className="flex items-center gap-3 p-2 bg-black/30 rounded-lg border border-white/5">
              <div className="w-20 h-11 rounded overflow-hidden shrink-0 border border-white/15 bg-slate-950 shadow-inner">
                <img
                  src={salon1Details.imageUrl}
                  alt="Previa del fondo"
                  className="w-full h-full object-cover"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div className="text-[10px] min-w-0 flex-1">
                <span className="text-slate-400 block font-mono">Arquetipo activo:</span>
                <span className="text-slate-200 block font-semibold truncate text-[11px] tracking-wide mt-0.5">
                  {s1CustomPrompt}
                </span>
              </div>
            </div>

          </div>
        </div>
      </div>

      {/* Salon 2 setup */}
      <div className="p-5 glass-card rounded-xl space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-white/10">
          <div className="w-5 h-5 rounded-full bg-cyan-500/20 text-cyan-300 text-xs font-bold flex items-center justify-center border border-cyan-500/20">2</div>
          <h3 className="font-semibold text-white text-sm">Salón Secundario (Exterior / Jardín / Terraza)</h3>
        </div>

        <div className="grid grid-cols-2 gap-3 text-xs">
          <div>
            <label className="block font-medium text-slate-350 mb-1">Nombre Comercial</label>
            <input
              type="text"
              value={salon2Details.name}
              onChange={(e) => setSalon2Details({ ...salon2Details, name: e.target.value })}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 focus:ring-1 focus:ring-cyan-500 text-white font-sans outline-hidden bg-black/30 placeholder-slate-400"
            />
          </div>
          <div>
            <label className="block font-medium text-slate-350 mb-1">Estilo / Concepto</label>
            <input
              type="text"
              value={salon2Details.style}
              onChange={(e) => setSalon2Details({ ...salon2Details, style: e.target.value })}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 focus:ring-1 focus:ring-cyan-500 text-white font-sans outline-hidden bg-black/30 placeholder-slate-400"
            />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-3 text-xs">
          <div>
            <label className="block font-medium text-slate-350 mb-1">Capacidad Máxima (personas)</label>
            <input
              type="number"
              value={salon2Details.capacity}
              onChange={(e) => setSalon2Details({ ...salon2Details, capacity: parseInt(e.target.value) || 0 })}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 focus:ring-1 focus:ring-cyan-500 text-white font-sans outline-hidden bg-black/30 placeholder-slate-400"
            />
          </div>
          <div>
            <label className="block font-medium text-slate-350 mb-1">Precio Base por Hora ($)</label>
            <input
              type="number"
              value={salon2Details.basePrice}
              onChange={(e) => setSalon2Details({ ...salon2Details, basePrice: parseInt(e.target.value) || 0 })}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 focus:ring-1 focus:ring-cyan-500 text-white font-sans outline-hidden bg-black/30 placeholder-slate-400"
            />
          </div>
        </div>

        {/* Amenities tag list */}
        <div className="text-xs">
          <label className="block font-medium text-slate-350 mb-1">Amenidades del Salón 2</label>
          <div className="flex flex-wrap gap-1.5 mb-2">
            {salon2Details.amenities.map((amenity, idx) => (
              <span key={idx} className="inline-flex items-center gap-1 px-2 py-0.5 bg-cyan-500/20 border border-cyan-500/30 text-cyan-300 rounded-md font-sans text-xs">
                {amenity}
                <button onClick={() => removeAmenity(2, idx)} className="text-cyan-400 hover:text-cyan-300 font-bold p-px cursor-pointer">&times;</button>
              </span>
            ))}
          </div>
          <div className="flex gap-1.5">
            <input
              type="text"
              placeholder="Ej. Piscina infinity, Jardines florales"
              value={newS2Amenity}
              onChange={(e) => setNewS2Amenity(e.target.value)}
              className="flex-1 px-2.5 py-1.5 rounded-lg border border-white/10 text-white font-sans text-xs bg-black/30 outline-hidden placeholder-slate-450"
              onKeyDown={(e) => e.key === "Enter" && addAmenity(2)}
            />
            <button
              onClick={() => addAmenity(2)}
              className="px-2.5 py-1.5 bg-cyan-600 hover:bg-cyan-700 text-white rounded-lg cursor-pointer transition-colors border border-white/10"
            >
              <Plus className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Generador de Imagen de Contexto (Hero Background) */}
        <div className="pt-4 border-t border-white/10 text-xs space-y-3">
          <div className="flex items-center gap-1.5 text-cyan-300 font-semibold text-xs">
            <ImageIcon className="w-4 h-4 text-cyan-400 shrink-0" />
            <span>Fondo de Contexto con IA (Hero Background)</span>
          </div>
          <p className="text-[11px] text-slate-400 leading-relaxed font-sans">
            Define el estilo visual del fondo para este salón. Elige una opción preestablecida o escribe un estilo personalizado para actualizar la landing page.
          </p>

          <div className="space-y-2">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
              <div>
                <label className="block text-[10px] text-slate-400 mb-1 font-sans">Estilo o Plantilla:</label>
                <select
                  value={s2StyleSelection}
                  onChange={(e) => {
                    setS2StyleSelection(e.target.value);
                    if (e.target.value !== "custom") {
                      setS2CustomPrompt(e.target.value);
                    } else {
                      setS2CustomPrompt("");
                    }
                  }}
                  className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white font-sans bg-slate-900 outline-hidden"
                >
                  <option value="Cóctel corporativo al atardecer en terraza minimalista">Cóctel de gala al atardecer 🌅</option>
                  <option value="Bodas de gala en salón de cristal">Bodas de gala en salón de cristal 💎</option>
                  <option value="Graduaciones elegantes de noche con luces de neón">Graduaciones elegantes de noche 🎓</option>
                  <option value="Quince años mágicos con luces cálidas colgantes">Quince años de cuento de hadas ✨</option>
                  <option value="Estilo Clásico de Palacio Europeo Imperial">Clásico Palacio Europeo 🏛️</option>
                  <option value="custom">Escribir estilo personalizado... ✍️</option>
                </select>
              </div>

              {s2StyleSelection === "custom" ? (
                <div>
                  <label className="block text-[10px] text-slate-400 mb-1 font-sans font-medium text-cyan-405">Describe tu estilo personalizado:</label>
                  <input
                    type="text"
                    placeholder="Ej. Fiesta temática rústico-industrial en la selva"
                    value={s2CustomPrompt}
                    onChange={(e) => setS2CustomPrompt(e.target.value)}
                    className="w-full px-2.5 py-1.5 rounded-lg border border-cyan-500/30 text-white font-sans bg-slate-900 outline-hidden placeholder-slate-500"
                  />
                </div>
              ) : (
                <div>
                  <label className="block text-[10px] text-slate-400 mb-1 font-sans">Estilo seleccionado:</label>
                  <div className="px-2.5 py-1.5 rounded-lg border border-white/10 text-slate-300 font-sans bg-black/20 italic truncate select-none">
                    "{s2CustomPrompt}"
                  </div>
                </div>
              )}
            </div>

            <div className="flex items-center justify-between pt-1 gap-2">
              <button
                type="button"
                onClick={() => handleImageGeneration(2)}
                disabled={s2Generating || !s2CustomPrompt.trim()}
                className="px-3 py-2 bg-gradient-to-r from-cyan-600 to-sky-600 hover:from-cyan-500 hover:to-sky-500 text-white font-bold rounded-lg cursor-pointer transition-all duration-250 flex items-center gap-1.5 disabled:opacity-40 select-none shadow-md shadow-cyan-950/20"
              >
                {s2Generating ? (
                  <>
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    <span>Generando Imagen con IA...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Generar Background con IA</span>
                  </>
                )}
              </button>

              {s2Success && (
                <span className="text-[10px] text-cyan-450 font-semibold animate-pulse bg-cyan-500/10 px-2 py-1 rounded-md border border-cyan-500/20">
                  ✓ Fondo aplicado con éxito
                </span>
              )}
            </div>
            
            {/* Image Preview Thumbnail */}
            <div className="flex items-center gap-3 p-2 bg-black/30 rounded-lg border border-white/5">
              <div className="w-20 h-11 rounded overflow-hidden shrink-0 border border-white/15 bg-slate-950 shadow-inner">
                <img
                  src={salon2Details.imageUrl}
                  alt="Previa del fondo"
                  className="w-full h-full object-cover"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div className="text-[10px] min-w-0 flex-1">
                <span className="text-slate-400 block font-mono">Arquetipo activo:</span>
                <span className="text-slate-200 block font-semibold truncate text-[11px] tracking-wide mt-0.5">
                  {s2CustomPrompt}
                </span>
              </div>
            </div>

          </div>
        </div>
      </div>

      {/* Target audience and Campaign vibe mapping */}
      <div className="p-5 glass-card rounded-xl space-y-4">
        <h3 className="font-semibold text-white text-sm">Objetivos de la Campaña</h3>

        <div className="text-xs space-y-3">
          <div>
            <label className="block font-medium text-slate-350 mb-1">Público Objetivo (Segmento de Mercado)</label>
            <input
              type="text"
              value={targetAudience}
              onChange={(e) => setTargetAudience(e.target.value)}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white font-sans bg-black/30 outline-hidden placeholder-slate-400"
              placeholder="Ej. Bodas, Eventos corporativos de lujo"
            />
          </div>

          <div>
            <label className="block font-medium text-slate-350 mb-1">Tono de la Landing Page</label>
            <select
              value={promoVibe}
              onChange={(e) => setPromoVibe(e.target.value)}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-slate-205 font-sans bg-slate-900 outline-hidden focus:ring-1 focus:ring-indigo-500"
            >
              <option value="Elegante y Sofisticado">Elegante y Sofisticado (Premium, ideal bodas corporativo)</option>
              <option value="Festivo y Alegre">Festivo y Alegre (Cumpleaños y celebraciones familiares)</option>
              <option value="Moderno y Disruptivo">Moderno e Industrial (Para congresos y activaciones)</option>
              <option value="Accesible y Familiar">Accesible y Familiar (Fiestas infantiles o bautizos)</option>
            </select>
          </div>
        </div>

        {error && (
          <div className="p-3 bg-rose-500/10 border border-rose-500/20 text-xs text-rose-300 rounded-lg">
            {error}
          </div>
        )}

        <button
          onClick={handleGenerateCopy}
          disabled={loading}
          className="w-full py-2.5 px-4 bg-gradient-to-r from-indigo-500 to-emerald-500 hover:opacity-90 text-white rounded-xl shadow-md font-semibold text-xs flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50 transition-all border border-white/10"
        >
          {loading ? (
            <>
              <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
              <span>Redactando con Inteligencia Artificial...</span>
            </>
          ) : (
            <>
              <MessageSquareCode className="w-4 h-4" />
              <span>Generar Redacción y Paquetes con IA Gemini</span>
            </>
          )}
        </button>
      </div>

      {/* Manual Content tweaking area */}
      <div className="p-5 glass-card rounded-xl space-y-4">
        <h3 className="font-semibold text-white text-sm flex items-center gap-1.5 pb-2 border-b border-white/10 flex-wrap md:flex-nowrap">
          <Edit className="w-4 h-4 text-indigo-400" />
          Editor Directo de Redacción
        </h3>

        <div className="text-xs space-y-3">
          <div>
            <label className="block font-medium text-slate-350 mb-1">Título de la Portada (Hero Title)</label>
            <input
              type="text"
              value={landingCopy.heroTitle}
              onChange={(e) => updateCopyField("heroTitle", e.target.value)}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white font-sans bg-black/30 outline-hidden"
            />
          </div>

          <div>
            <label className="block font-medium text-slate-350 mb-1">Subtítulo de la Portada</label>
            <textarea
              rows={2}
              value={landingCopy.heroSubtitle}
              onChange={(e) => updateCopyField("heroSubtitle", e.target.value)}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white font-sans bg-black/30 outline-hidden resize-none animate-none"
            />
          </div>

          <div>
            <label className="block font-medium text-slate-350 mb-1">Frase Comparativa (Hook de comparación)</label>
            <input
              type="text"
              value={landingCopy.comparativeHook}
              onChange={(e) => updateCopyField("comparativeHook", e.target.value)}
              className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white font-sans bg-black/30 outline-hidden"
            />
          </div>

          <div className="pt-2 border-t border-white/10">
            <h4 className="font-medium text-emerald-305 mb-2">{salon1Details.name}</h4>
            <div className="space-y-2">
              <div>
                <label className="block text-slate-400 mb-1 font-sans text-[11px]">Slogan de Entrada</label>
                <input
                  type="text"
                  value={landingCopy.salon1HeroCopy}
                  onChange={(e) => updateCopyField("salon1HeroCopy", e.target.value)}
                  className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white bg-black/30 outline-hidden"
                />
              </div>
              <div>
                <label className="block text-slate-400 mb-1 font-sans text-[11px]">Descripción Detallada</label>
                <textarea
                  rows={3}
                  value={landingCopy.salon1Description}
                  onChange={(e) => updateCopyField("salon1Description", e.target.value)}
                  className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white bg-black/30 outline-hidden resize-none animate-none"
                />
              </div>
            </div>
          </div>

          <div className="pt-2 border-t border-white/10">
            <h4 className="font-medium text-cyan-305 mb-2">{salon2Details.name}</h4>
            <div className="space-y-2">
              <div>
                <label className="block text-slate-400 mb-1 font-sans text-[11px]">Slogan de Entrada</label>
                <input
                  type="text"
                  value={landingCopy.salon2HeroCopy}
                  onChange={(e) => updateCopyField("salon2HeroCopy", e.target.value)}
                  className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white bg-black/30 outline-hidden"
                />
              </div>
              <div>
                <label className="block text-slate-400 mb-1 font-sans text-[11px]">Descripción Detallada</label>
                <textarea
                  rows={3}
                  value={landingCopy.salon2Description}
                  onChange={(e) => updateCopyField("salon2Description", e.target.value)}
                  className="w-full px-2.5 py-1.5 rounded-lg border border-white/10 text-white bg-black/30 outline-hidden resize-none animate-none"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
